default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reports-api_development
test:
  <<: *default
  database: reports-api_test
production:
  <<: *default
  database: reports-api_production
  username: reports-api
  password: <%= ENV['REPORTS-API_DATABASE_PASSWORD'] %>
